language: node_js
node_js:
  - '14'
os: linux
dist: bionic
notifications:
  email:
    recipients:
      - raaed.kabir@gmail.com
    on_success: always
    on_failure: always
cache:
  npm: true
  directories:
    - node_modules
before_deploy:
  - npm i -g travis-ci-cloudfront-invalidation
  - npm run generate
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: ap-southeast-1
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
